export { default as AdminLayout } from './AdminLayout'
export { default as CreateProducts } from './CreateProducts'
export { default as Dashboard } from './Dashboard'
export { default as ManageProducts } from './ManageProducts'
export { default as ManagerOrder } from './ManagerOrder'
export { default as ManageUser } from './ManageUser'